spring:
  application:
    name: seguridad
  datasource:
    #url: jdbc:postgresql://${postgres_server}:5432/seguridad
    url: jdbc:postgresql://localhost:5432/seguridad
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true  
    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop

#Component Info  
info:
  component: seguridad

#Port - If 0 get random port
server:
# port: 8080
#server: 
 port: 0
 
