spring:
  application:
    name: seguridad
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 20000
      poolName: poolSeguridad    
  jpa:
    generate-ddl: true  
    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop

#Component Info  
info:
  component: seguridad

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: gateway,health,info
        
#Port - If 0 get random port
server:
 port: 8089
#server: 
# port: 0
 