spring:
  application:
    name: seguridad
  datasource:
    #url: jdbc:postgresql://${postgres_server}:5432/seguridad
    url: jdbc:postgresql://clusterdbdllo.cluster-cbg8artgeyju.us-east-2.rds.amazonaws.com:5432/DBDLLO
    username: core_application
    password: c0r3_4ppl1c4t10n
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
      poolName: poolSeguridad    
  jpa:
    generate-ddl: true  
    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop

#  profiles: test
  
#Component Info  
info:
  component: seguridad

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: gateway,health,info
        
#Port - If 0 get random port
server:
#    servlet:
#        contextPath: /api
    port: 8089
     
#server: 
# port: 0
 