spring:
  application:
    name: seguridad
  datasource:
    #url: jdbc:postgresql://${postgres_server}:5432/seguridad
    url: jdbc:postgresql://instancedbdllo.cbg8artgeyju.us-east-2.rds.amazonaws.com:5432/DBDLLO
    username: core_application
    password: c0r3_4ppl1c4t10n
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true  
    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop

#Component Info  
info:
  component: seguridad

#Port - If 0 get random port
server:
 port: 8089
#server: 
# port: 0
 