spring:
  application:
    name: seguridad
  datasource:
    url: jdbc:postgresql://instancedbdllo.clq0hirggvto.us-east-1.rds.amazonaws.com:5432/DBDEV
    username: core_application
    password: c0r3_4ppl1c4t10n
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 6
      idle-timeout: 10000
      poolName: poolSeguridad    
  jpa:
    generate-ddl: true  
    show-sql: true
#    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      ddl-auto: create-drop

#Component Info  
info:
  component: seguridad

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: gateway,health,info
        
#Port - If 0 get random port
server:
 port: 8089
#server: 
# port: 0
 